version: '2'

services:
  
  formio-app:
    image: tiredofit/formio-app
    container_name: formio-app
    volumes:
    - ./data:/app
    environment:
    - VIRTUAL_HOST=formio-app.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=formio-app.example.com
    - LETSENCRYPT_EMAIL=email@example.com

    - ZABBIX_HOSTNAME=formio-app

    - REVERSE_PROXY=true
    - APP=movies
    
    - API_HOST=api.formio.example.com
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

