version: '2'

services:
  
  formio-api-app:
    image: tiredofit/formio-api
    container_name: formio-api-app
    volumes:
    - ./templates:/app/templates
    environment:
    - VIRTUAL_HOST=formio.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=3001
    - LETSENCRYPT_HOST=formio.example.com
    - LETSENCRYPT_EMAIL=email@example.com

    - ZABBIX_HOSTNAME=formio-app

    - DB_HOST=formio-db-mongo

    - ROOT_EMAIL=admin@example.com
    - ROOT_PASS=password

    - DEBUG_MODE=FALSE
    - PROJECT_TEMPLATE=default
    networks:
      - proxy-tier
    restart: always

  formio-db-mongo:
    container_name: formio-db-mongo
    image: mongo
    restart: unless-stopped
    volumes:
     - ./db:/data/db
    command: mongod --smallfiles
    networks:
      - proxy-tier
    environment:
      - ZABBIX_HOSTNAME=formio-db-mongo

  formio-db-mongo-backup:
    container_name: formio-db-mongo-backup
    image: tiredofit/db-backup
    links:
     - formio-db-mongo
    volumes:
      - ./dbbackup:/backups
    environment:
      - DB_TYPE=mongo
      - DB_HOST=formio-db-mongo
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=GZ

    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

